INSERT INTO books (book_title, book_author, book_description, book_category) VALUES
('The Quantum Paradox', 'Elena Rostova', 'A gripping sci-fi thriller about a physicist who accidentally tears a hole in the fabric of time.', 'Sci-Fi'),
('Echoes of the Forgotten', 'Marcus Vance', 'An archeologist discovers an ancient city buried beneath the sands of the Sahara that should not exist.', 'Adventure'),
('Mindset Over Matter', 'Dr. Aris Thorne', 'A practical guide to rewriting your cognitive habits and achieving peak mental performance.', 'Self-Help'),
('The Clockwork Kingdom', 'Cynthia Weaver', 'In a steampunk world, a young mechanic must protect the royal family from an army of rogue automatons.', 'Fantasy'),
('Beneath Neon Skies', 'Kaito Tanaka', 'A hard-boiled detective hunts a cybernetic assassin through the rainy streets of neo-Tokyo.', 'Sci-Fi'),
('Whispers in the Woods', 'Sarah Jenkins', 'A psychological horror novel about a family that moves into a remote cabin with a dark history.', 'Horror'),
('The Art of Resilience', 'Julian Mercer', 'Lessons drawn from historical figures on how to survive and thrive during chaotic times.', 'Self-Help'),
('Midnight at the Cafe', 'Chloe Laurent', 'A heartwarming romance about two strangers who keep meeting at a 24-hour Parisian coffee shop.', 'Romance'),
('The Last Emperor of Rome', 'Prof. Alistair Cross', 'A comprehensive historical biography detailing the chaotic final days of the Western Roman Empire.', 'History'),
('Shadows of the Citadel', 'Gareth Blackwood', 'An exiled assassin is hired to break into the most secure fortress in the kingdom.', 'Fantasy'),
('Stellar Horizon', 'Tariq Mahmood', 'Humanity’s first interstellar colony ship faces mutiny when they discover they aren’t alone.', 'Sci-Fi'),
('The Girl Who Caught the Wind', 'Maya Lin', 'A beautifully poetic coming-of-age story set in a small fishing village in Taiwan.', 'Drama'),
('Deception Point Zero', 'Robert Vance', 'A political thriller involving a missing senator and a conspiracy that reaches the White House.', 'Thriller'),
('Atomic Focus', 'James Clearfield', 'How micro-habits can compound into massive life transformations over a twelve-month period.', 'Self-Help'),
('The Alchemist’s Daughter', 'Sophia Rossi', 'A historical fiction novel set in Renaissance Florence following a woman practicing forbidden science.', 'Historical Fiction'),
('Crimson Tides', 'Captain Arthur Flint', 'A gritty, high-seas pirate adventure filled with betrayal, hidden treasure, and naval warfare.', 'Adventure'),
('Algorithms of the Heart', 'Zoe Chen', 'A quirky romantic comedy about a data scientist who codes an algorithm to find her perfect match.', 'Romance'),
('The Forgotten Trenches', 'Christian Dupont', 'An intimate and devastating look into the lives of soldiers during the winter of 1916.', 'History'),
('Legends of the World Tree', 'Freja Lindstrom', 'A Norse-inspired epic fantasy where the gods are dying and a shieldmaiden must take their place.', 'Fantasy'),
('Digital Ghost', 'Lucas Kane', 'An elite hacker is framed for a global cyberattack and must run from both Interpol and the mob.', 'Thriller'),
('The Daily Reset', 'Miriam Gallagher', 'A 365-day journal filled with prompts designed to reduce anxiety and promote mindfulness.', 'Self-Help'),
('Chasing Fireflies', 'Harper Lee-Walker', 'A nostalgic drama about three childhood friends reuniting in their small Southern hometown.', 'Drama'),
('Nebula Drifter', 'Jaxson Reed', 'A rogue spacescrapper accidentally steals a ship containing a weapon that could destroy the galaxy.', 'Sci-Fi'),
('The Poisoned Chalice', 'Lady Victoria Croft', 'A classic murder mystery set in an English manor during a rainy weekend estate party.', 'Mystery'),
('Songs of the Deep', 'Nerida Vance', 'A fantasy novel exploring an intricate underwater civilization facing an ecological crisis.', 'Fantasy'),
('The Silk Road Legacy', 'Dr. Henry Zheng', 'An academic exploration of the trade routes that shaped the medieval world’s economy.', 'History'),
('Love in Translation', 'Amara Okafor', 'An American journalist falls for her translator while on assignment in rural Japan.', 'Romance'),
('The Silent Patient Room', 'Dr. David Vance', 'A psychological thriller about an asylum psychiatrist obsessed with a patient who hasn’t spoken in years.', 'Thriller'),
('Beyond the Event Horizon', 'Neil Armstrong-Vance', 'An collection of essays exploring what modern physics says about black holes and wormholes.', 'Science'),
('The Chef’s Secret', 'Mateo Silva', 'A culinary fiction novel filled with romance, drama, and mouth-watering descriptions of Tuscan food.', 'Drama'),
('The Iron Throne of Britain', 'Simon Scarrow-Vance', 'A brutal and realistic historical fiction account of the Roman invasion of Britain.', 'Historical Fiction'),
('Unlocking Creativity', 'Gemma Styles', 'Exercises and routines designed to help artists break through creative blocks and imposter syndrome.', 'Self-Help'),
('The Witch of Endor', 'Rebecca Solnit', 'A dark fantasy reimagining of ancient folklore through a modern, feminist lens.', 'Fantasy'),
('Code Name: Dragonfly', 'Alexei Volkov', 'A Cold War espionage thriller about a double agent operating in East Berlin.', 'Thriller'),
('The Last Oasis', 'Nadia El-Amin', 'In a post-apocalyptic world dried of water, a nomad searches for a mythical endless spring.', 'Sci-Fi'),
('Stargazing for Beginners', 'Prof. Lucas Sky', 'A practical, fully illustrated guide to identifying constellations and planets from your backyard.', 'Science'),
('The Billionaire’s Gamble', 'Penelope Ward-Vance', 'A witty enemies-to-lovers romance set in the high-stakes corporate world of New York real estate.', 'Romance'),
('Ghosts of New Orleans', 'Jackson Cole', 'A supernatural mystery following a detective who can see the spirits of unsolved murder victims.', 'Mystery'),
('The Renaissance Mind', 'Leonardo Vance', 'A deep dive into how art, science, and philosophy collided to pull Europe out of the Dark Ages.', 'History'),
('The Final Descent', 'Clara Higgins', 'A tense survival thriller about a group of cave divers trapped in an uncharted underwater cavern.', 'Thriller');